### ISSUE TITLE
Document the dependency of running the prep.go script

### ISSUE THREAD

**Issue by santosomar** [TIBCOSoftware/vulnrep#2]
In order to download and prepare all the appropriate schema files used for testing run the prep.go script at: https://github.com/TIBCOSoftware/vulnrep/blob/master/cmd/prep/prep.go

This should be documented in the [README.md ](https://github.com/TIBCOSoftware/vulnrep/blob/master/README.md)

**Comment by ericjohnson-tibco** [comment]
README.md updated!
